"""Gradio entry point for the SatQuery MVP."""
from __future__ import annotations

import gradio as gr
from PIL import Image

from src.satquery.config import Settings
from src.satquery.service import SatQueryService

settings = Settings.from_environment()
service = SatQueryService(settings)


def answer(image: Image.Image | None, question: str, mode: str):
    if image is None:
        return "Please upload a satellite or aerial image first.", {}, "No evidence available."
    if not question or not question.strip():
        return "Please enter a question about the uploaded image.", {}, "No evidence available."
    result = service.ask(image, question.strip(), mode)
    summary = result.to_summary()
    return result.answer, summary, result.evidence_markdown()


css = """
.gradio-container {background: #07111f; color: #edf4ff;}
#hero {text-align:center; padding: 16px 8px 4px;}
#hero h1 {font-size: 2.3rem; margin-bottom: 0.2rem; color:#7dd3fc;}
#hero p {color:#b6c7dd; max-width:780px; margin:auto;}
.panel {border:1px solid #28445d; border-radius:16px; background:#0b1a2c;}
"""

with gr.Blocks(theme=gr.themes.Ocean(), css=css, title="SatQuery | SIH MVP") as demo:
    gr.HTML("""<div id='hero'><h1>🛰️ SatQuery</h1><p>Ask a natural-language question about a satellite or aerial image. Built as an SIH 2026 MVP.</p></div>""")
    gr.Markdown("**Demo note:** Answers are generated by a general visual question-answering model and should be treated as indicative, not geospatially verified analysis.")
    with gr.Row():
        with gr.Column(scale=1, elem_classes="panel"):
            image_input = gr.Image(type="pil", label="Upload satellite / aerial image", height=380)
            mode = gr.Radio(
                ["Local Hugging Face", "Hosted Hugging Face API"],
                value="Hosted Hugging Face API" if settings.default_mode == "api" else "Local Hugging Face",
                label="Inference mode",
            )
        with gr.Column(scale=1, elem_classes="panel"):
            question = gr.Textbox(
                label="Your question",
                placeholder="e.g., Is there a river visible in this image?",
                lines=3,
            )
            submit = gr.Button("Analyze image", variant="primary", size="lg")
            answer_out = gr.Textbox(label="SatQuery answer", lines=4, interactive=False)
    with gr.Row():
        route_out = gr.JSON(label="Task routing & model result", elem_classes="panel")
        evidence_out = gr.Markdown(label="Evidence & metadata", elem_classes="panel")
    gr.Examples(
        examples=[["Is there a road visible?"], ["What is the dominant land cover?"], ["Are buildings visible in this image?"], ["How many large objects can you see?"]],
        inputs=question,
        label="Example questions",
    )
    submit.click(answer, [image_input, question, mode], [answer_out, route_out, evidence_out])
    question.submit(answer, [image_input, question, mode], [answer_out, route_out, evidence_out])


if __name__ == "__main__":
    demo.launch(server_name=settings.host, server_port=settings.port, show_error=True)
